---
- name: Install JBang via official script
  shell: |
    curl -Ls https://sh.jbang.dev | bash -s -
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.jbang/bin/jbang"

- name: Ensure JBang is available in PATH for all users
  copy:
    content: 'export PATH="$HOME/.jbang/bin:$PATH"'
    dest: /etc/profile.d/jbang.sh
    mode: '0644'

- name: Symlink jbang to /usr/local/bin for global use
  file:
    src: "{{ ansible_env.HOME }}/.jbang/bin/jbang"
    dest: /usr/local/bin/jbang
    state: link
    force: true
